@startuml
skinparam handwritten true
skinparam monochrome true
skinparam ArrowColor gray
skinparam DefaultFontSize 10
skinparam TitleFontSize 12

title 2 instances of sirius-chat ...

foo -> (traefik)
bar -left-> (traefik)
(traefik) ---> (sirius-chat-1): foo's\nsession
(traefik) ---> (sirius-chat-2): bar's\nsession
(sirius-chat-1) --> (Redis)
(sirius-chat-1) --> (Elasticsearch)
(sirius-chat-2) --> (Redis)
(sirius-chat-2) --> (Elasticsearch)

@enduml