@startuml
skinparam handwritten true
skinparam monochrome true
skinparam ArrowColor gray
skinparam DefaultFontSize 10

User1 -> (traefik)
User2 -left-> (traefik)
(traefik) --> (sirius-chat-1): session\nUser1
(traefik) --> (sirius-chat-2): session\nUser2
(sirius-chat-1) --> (Redis)
(sirius-chat-1) --> (Elasticsearch)
(sirius-chat-2) --> (Redis)
(sirius-chat-2) --> (Elasticsearch)

@enduml