@startuml
skinparam handwritten true
skinparam monochrome true
skinparam ArrowColor gray
skinparam DefaultFontSize 10
skinparam TitleFontSize 12
skinparam usecase {
    BackGroundColor<< dead >> lightgray
    FontColor<< dead >> red
}
skinparam Note {
    FontName Arial
    FontStyle bold
    FontSize 11
    FontColor white
    BackGroundColor gray
}
title ... after sirius-chat-2 'crashes'

:User1: -> (traefik)
:User2: -left-> (traefik)
(traefik) --> (sirius-chat-1): foo's\nsession
note "new bar's\nsession" as RD
(traefik) .. RD
RD ..> (sirius-chat-1)
(sirius-chat-2) << dead >>
(sirius-chat-1) --> (Redis)
(sirius-chat-1) --> (Elasticsearch)

@enduml